### ISSUE TITLE
Unable to sink data with PosgreSQL source

### ISSUE THREAD

**Issue by thailb-developer** [jcustenborder/kafka-connect-redis#47]
Hi Team.

I am trying to setup the data flow as:
* Source: PostgreSQL, using `io.debezium.connector.postgresql.PostgresConnector`
* Sink: Redis, using `com.github.jcustenborder.kafka.connect.redis.RedisSinkConnector`

Here is my `docker-compose` to start services.
```
version: "3.8"
services:
  content_sql:
    container_name: content_sql
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: content_admin
      POSTGRES_PASSWORD: 123456xyz
      POSTGRES_DB: madison_content
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - 5432:5432
    restart: always

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - 6379:6379

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.8-temurin
    environment:
      JVMFLAGS: -XX:+UseG1GC -XX:+DisableExplicitGC
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    restart: always

  kafka:
    container_name: kafka
    image: ubuntu/kafka:edge
    environment:
      TZ: UTC
      ZOOKEEPER_HOST: host.docker.internal
      ZOOKEEPER_PORT: 2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    restart: always

  kafka_connector:
    container_name: kafka_connector
    image: debezium/connect-base:latest
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: content_configs
      OFFSET_STORAGE_TOPIC: cache_content
      STATUS_STORAGE_TOPIC: connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
      KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      KAFKA_CONNECT_PLUGINS_DIR: /usr/share/local-connectors
    volumes:
      - ~/Documents/kafka-plugins:/usr/share/local-connectors
    ports:
      - 8083:8083
    depends_on:
      - content_sql
      - kafka
      - redis
      - zookeeper
    restart: always
```

The `docker-compose` can start successfully and plugins are loaded correctly.

Here is my REST request to register the connector.

PostgreSQL Source
```
{
	"name": "postgres-source",
	"config": {
		"connector.class": "io.debezium.connector.postgresql.PostgresConnector",
		"task.max": "3",
		"database.hostname": "content_sql",
		"database.port": "5432",
		"database.user": "content_admin",
		"database.password": "123456xyz",
		"database.dbname": "madison_content",
		"database.whitelist": "madison_content",
		"table.include.list": "public.thread",
		"topic.prefix": "cache",
		"schema.history.internal.kafka.bootstrap.servers": "kafka:9092",
		"plugin.name": "pgoutput"
	}
}
```

Redis Sink
```
{
	"name": "redis-sink",
	"config": {
		"connector.class": "com.github.jcustenborder.kafka.connect.redis.RedisSinkConnector",
		"redis.hosts": "redis:6379",
		"redis.database": "1",
		"redis.client.mode": "Standalone",
		"task.max": "3",
		"key.converter": "org.apache.kafka.connect.storage.StringConverter",
		"internal.key.converter": "org.apache.kafka.connect.storage.StringConverter",
		"value.converter": "org.apache.kafka.connect.storage.StringConverter",
		"internal.value.converter": "org.apache.kafka.connect.storage.StringConverter",
		"plugin.path": "/usr/share/local-connectors",
		"topics.regex": "cache.(.*)"
	}
}
```

When I inserted data to PostgreSQL, I noticed that INFO log showed "N records ..." , I also double-checked manually the Kafka topic and message. The topic was created successfully, message was there. But somehow, the sink never work.

May you please help to have a look? Thanks.
